### ISSUE TITLE
Option to configure how many sentences per line are allowed

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/sentences-per-line#26]
Some setups would want to have, say, 2 sentences per line. This should be configurable.

**Comment by JoshuaKGoldberg** [comment]
Removing `good first issue` as this is really more of a feature request.

**Comment by waldyrious** [comment]
> Some setups would want to have, say, 2 sentences per line. 

I'm curious, what could be the rationale for that? :thinking:

**Comment by JoshuaKGoldberg** [comment]
Haha good question. It's been a couple years and I don't remember specifics... I think the general thought was that if exactly one line is too strict, roughly two would be easier for onboarding. Do you think this should be closed?

**Comment by waldyrious** [comment]
I can't really get into the shoes of someone thinking that limiting one line to contain a single sentence would be too rigid, but allowing two per line (but not, say, three) would be acceptable. Perhaps the uneasiness might stem from line length (due to very short sentences), rather than number of sentences?

Either way, if you also aren't convinced that the reasoning is compelling, then yeah, I'd recommend closing the issue for now, and reopening later if others chime in with additional insight that would make the case stronger.
